// F38 / F39 / F40: parsing pasted cookie exports and shaping the cookies.set
// calls that reproduce them. Chromium's rules that bit are modelled in a tiny
// jar below: a __Host- cookie with a Domain is rejected, a host-only cookie
// written with a Domain becomes a domain cookie, and removal happens before
// writes. Run: npm test
const test = require('node:test');
const assert = require('node:assert/strict');
const {
  parseCookieBlob, normalizeExpiry, isHostOnlyCookie, cookieSetDetails, planCookieWrites,
  shouldClearExisting, removalUrl, isYouTubeCookieDomain, assignPastedYouTubeDomains, hasGoogleSessionCookies,
  youtubeJarCookies, isCookieHost, isCookieDomainOf, applyCookiePlan,
} = require('../main/cookie-import');
const { createSyncTickets } = require('../main/account-state');

const NOW_S = 1_800_000_000;
const ONE_YEAR_S = 60 * 60 * 24 * 365;

// A curl-style cookies.txt, as "Get cookies.txt LOCALLY" writes it: httpOnly
// cookies carry a #HttpOnly_ prefix, CRLF line ends, a session cookie has 0.
const NETSCAPE = [
  '# Netscape HTTP Cookie File',
  '# This file was generated by Get cookies.txt LOCALLY',
  '',
  '#HttpOnly_.google.com\tTRUE\t/\tTRUE\t1830000000\tSID\tsid-google',
  '#HttpOnly_.google.com\tTRUE\t/\tTRUE\t1830000000\tHSID\thsid-google',
  '#HttpOnly_.google.com\tTRUE\t/\tTRUE\t1830000000\tSSID\tssid-google',
  '#HttpOnly_.google.com\tTRUE\t/\tTRUE\t1830000000\t__Secure-1PSID\tpsid-google',
  '.google.com\tTRUE\t/\tTRUE\t1830000000\tSAPISID\tsapisid-google ',
  '.youtube.com\tTRUE\t/\tTRUE\t0\tYSC\tysc-session',
  '#HttpOnly_accounts.google.com\tFALSE\t/\tTRUE\t1830000000\t__Host-GAPS\tgaps',
  'www.youtube.com\tFALSE\t/\tFALSE\t1830000000\tPREF\tf6=40000000',
].join('\r\n');

test('F38: cookies.txt keeps #HttpOnly_ lines as httpOnly cookies and still skips real comments', () => {
  const out = parseCookieBlob(NETSCAPE);
  const byName = Object.fromEntries(out.map(c => [c.name, c]));
  assert.deepEqual(Object.keys(byName).sort(), ['HSID', 'PREF', 'SAPISID', 'SID', 'SSID', 'YSC', '__Host-GAPS', '__Secure-1PSID']);
  assert.equal(byName.SID.httpOnly, true);
  assert.equal(byName.SID.domain, '.google.com', 'prefix stripped, domain intact');
  assert.equal(byName['__Secure-1PSID'].httpOnly, true);
  assert.equal(byName.SAPISID.httpOnly, false);
  assert.equal(byName.SAPISID.value, 'sapisid-google', 'trailing whitespace trimmed');
  assert.equal(byName.YSC.expirationDate, undefined, 'expiry 0 is a session cookie');
  assert.equal(byName['__Host-GAPS'].domain, 'accounts.google.com');
  assert.equal(byName['__Host-GAPS'].hostOnly, true, 'includeSubdomains FALSE on a dotless domain');
  assert.equal(byName.PREF.hostOnly, true);
  assert.equal(byName.SID.hostOnly, false);
  // The import gate now passes on the real session identifiers...
  assert.equal(hasGoogleSessionCookies(out), true);
  // ...and the same file with its httpOnly lines lost (what the old parser
  // produced) is refused instead of reported as a success.
  const stripped = parseCookieBlob(NETSCAPE.split('\r\n').filter(l => !l.startsWith('#HttpOnly_')).join('\n'));
  assert.equal(hasGoogleSessionCookies(stripped), false);
});

test('F38: a leading dot means a domain cookie whatever the flag says; TRUE on a dotless domain too', () => {
  const out = parseCookieBlob('.kick.com\tFALSE\t/\tTRUE\t1830000000\ta\t1\nkick.com\tTRUE\t/\tTRUE\t1830000000\tb\t2');
  assert.equal(out[0].hostOnly, false);
  assert.equal(out[1].hostOnly, false);
  assert.equal(cookieSetDetails(out[1], { nowS: NOW_S }).domain, 'kick.com', 'kept as a domain cookie');
});

test('F38: JSON expiry: -1, 0, milliseconds, date strings, session flag', () => {
  const out = parseCookieBlob(JSON.stringify([
    { name: 'a', value: '1', domain: '.youtube.com', expires: -1 },
    { name: 'b', value: '1', domain: '.youtube.com', expires: 0 },
    { name: 'c', value: '1', domain: '.youtube.com', expires: 1830000000123 },
    { name: 'd', value: '1', domain: '.youtube.com', expires: '2028-01-01T00:00:00Z' },
    { name: 'e', value: '1', domain: '.youtube.com', expirationDate: 1830000000.5 },
    { name: 'f', value: '1', domain: '.youtube.com', expirationDate: 1830000000, session: true },
    { name: 'g', value: '1', domain: 'www.youtube.com', hostOnly: true, expirationDate: -1 },
  ]));
  const exp = Object.fromEntries(out.map(c => [c.name, c.expirationDate]));
  assert.equal(exp.a, undefined);
  assert.equal(exp.b, undefined);
  assert.equal(exp.c, 1830000000.123);
  assert.equal(exp.d, Date.parse('2028-01-01T00:00:00Z') / 1000);
  assert.equal(exp.e, 1830000000.5);
  assert.equal(exp.f, undefined);
  assert.equal(out.find(c => c.name === 'g').hostOnly, true);
  // A session cookie written as -1 would be dropped by Chromium on the spot;
  // it gets the writer's one-year default instead.
  assert.equal(cookieSetDetails(out[0], { nowS: NOW_S }).expirationDate, NOW_S + ONE_YEAR_S);
  assert.equal(cookieSetDetails({ name: 'x', value: '1', domain: '.a.com', expirationDate: -1 }, { nowS: NOW_S }).expirationDate, NOW_S + ONE_YEAR_S);
});

test('normalizeExpiry: far-future seconds stay seconds; only raw numbers can be milliseconds', () => {
  const NEVER = 253402300799; // 9999-12-31T23:59:59Z, the usual "never expires"
  assert.equal(normalizeExpiry(NEVER), NEVER);
  assert.equal(normalizeExpiry(String(NEVER)), NEVER);
  assert.equal(normalizeExpiry('9999-12-31T23:59:59Z'), NEVER, 'a parsed date is never divided again');
  assert.equal(normalizeExpiry('Fri, 31 Dec 9999 23:59:59 GMT'), NEVER);
  assert.equal(normalizeExpiry(1830000000000), 1830000000, 'milliseconds');
  assert.equal(normalizeExpiry('1830000000000'), 1830000000);
  assert.equal(normalizeExpiry(1830000000.5), 1830000000.5, 'Chrome writes fractional seconds');
  assert.ok(normalizeExpiry(NEVER) > Date.now() / 1000, 'a never-expiring cookie is not written expired');
});

test('normalizeExpiry rejects everything that is not a positive time', () => {
  for (const v of [undefined, null, '', 'Session', NaN, Infinity, -5, 0, '0', {}, []]) {
    assert.equal(normalizeExpiry(v), undefined, String(v));
  }
  assert.equal(normalizeExpiry('1830000000'), 1830000000);
});

test('F39: __Host- cookies are written without a Domain, on path /, secure', () => {
  // As the extension sends it: chrome.cookies domain, no hostOnly field.
  const d = cookieSetDetails({ name: '__Host-GAPS', value: 'g', domain: 'accounts.google.com', path: '/', secure: true, httpOnly: true, sameSite: 'lax', expirationDate: 1830000000 }, { defaultDomain: '.youtube.com', nowS: NOW_S });
  assert.equal('domain' in d, false, 'no domain key at all');
  assert.equal(d.url, 'https://accounts.google.com/');
  assert.equal(d.path, '/');
  assert.equal(d.secure, true);
  assert.equal(d.httpOnly, true);
  // Even an exporter that got the path or the secure flag wrong.
  const odd = cookieSetDetails({ name: '__Host-1PLSID', value: 'x', domain: 'accounts.google.com', path: '/x', secure: false }, { nowS: NOW_S });
  assert.equal(odd.path, '/');
  assert.equal(odd.secure, true);
  assert.equal('domain' in odd, false);
  assert.equal(cookieSetDetails({ name: '__Secure-3PSID', value: 'x', domain: '.google.com', secure: false }, { nowS: NOW_S }).secure, true);
});

test('F39: host-only stays host-only, domain cookies keep their Domain, domain-less keeps the default', () => {
  const host = cookieSetDetails({ name: 'PREF', value: 'p', domain: 'www.youtube.com' }, { defaultDomain: '.youtube.com', nowS: NOW_S });
  assert.equal('domain' in host, false);
  assert.equal(host.url, 'https://www.youtube.com/');
  const dom = cookieSetDetails({ name: 'SID', value: 's', domain: '.youtube.com' }, { defaultDomain: '.youtube.com', nowS: NOW_S });
  assert.equal(dom.domain, '.youtube.com');
  assert.equal(dom.url, 'https://youtube.com/');
  const flagged = cookieSetDetails({ name: 'x', value: 'v', domain: 'kick.com', hostOnly: true }, { nowS: NOW_S });
  assert.equal('domain' in flagged, false);
  // A synthesized cookie with no domain of its own (the Twitch login cookie
  // path, a header paste) stays a domain cookie on the default, as before.
  const synth = cookieSetDetails({ name: 'login', value: 'me' }, { defaultDomain: '.twitch.tv', nowS: NOW_S });
  assert.equal(synth.domain, '.twitch.tv');
  assert.equal(cookieSetDetails({ name: 'n', value: 'v' }, {}), null, 'no domain anywhere');
  assert.equal(isHostOnlyCookie({ name: 'a', domain: '.x.com', hostOnly: true }), true, 'an explicit flag wins');
});

test('SameSite=None on an insecure cookie is downgraded instead of rejected', () => {
  const d = cookieSetDetails({ name: 'PREF', value: 'p', domain: 'www.youtube.com', secure: false, sameSite: 'no_restriction' }, { nowS: NOW_S });
  assert.equal(d.secure, false);
  assert.equal(d.sameSite, 'unspecified');
});

// Chromium's cookie store, reduced to the rules above.
function createJar(initial = []) {
  const cookies = initial.map(c => ({ ...c }));
  const key = (c) => `${c.name}|${c.domain}|${c.path}`;
  return {
    cookies,
    get({ name }) { return cookies.filter(c => c.name === name).map(c => ({ ...c })); },
    remove(url, name) {
      const u = new URL(url);
      for (let i = cookies.length - 1; i >= 0; i--) {
        const c = cookies[i];
        const host = c.domain.replace(/^\./, '');
        const matches = c.domain.startsWith('.') ? (u.hostname === host || u.hostname.endsWith('.' + host)) : u.hostname === host;
        if (c.name === name && matches && u.pathname.startsWith(c.path)) cookies.splice(i, 1);
      }
    },
    set(d) {
      if (d.name.startsWith('__Host-') && 'domain' in d) throw new Error('Failed to set cookie with an invalid domain attribute');
      const u = new URL(d.url);
      const c = { name: d.name, value: d.value, path: d.path, domain: 'domain' in d ? (d.domain.startsWith('.') ? d.domain : '.' + d.domain) : u.hostname, hostOnly: !('domain' in d) };
      const i = cookies.findIndex(x => key(x) === key(c));
      if (i >= 0) cookies.splice(i, 1);
      cookies.push(c);
    },
  };
}

function applyPlan(jar, list, defaultDomain) {
  const plan = planCookieWrites(list, { defaultDomain, nowS: NOW_S });
  for (const name of plan.clear.keys()) {
    for (const ex of jar.get({ name })) if (shouldClearExisting(ex, plan)) jar.remove(removalUrl(ex), name);
  }
  let count = 0;
  for (const d of plan.writes) { try { jar.set(d); count++; } catch (e) { /* counted as failed */ } }
  return count;
}

test('F39: one import can hold the same name on two hosts of a site; both survive', () => {
  const jar = createJar([
    { name: 'VISITOR', value: 'stale', domain: '.youtube.com', path: '/' },
    // What older builds wrote for a host-only cookie.
    { name: 'PREF', value: 'legacy', domain: '.www.youtube.com', path: '/' },
    { name: 'SID', value: 'other-site', domain: '.twitch.tv', path: '/' },
  ]);
  const count = applyPlan(jar, [
    { name: 'VISITOR', value: 'a', domain: '.youtube.com', path: '/' },
    { name: 'VISITOR', value: 'b', domain: 'm.youtube.com', path: '/' },
    { name: 'PREF', value: 'new', domain: 'www.youtube.com', path: '/' },
    { name: '__Host-GAPS', value: 'g', domain: 'accounts.google.com', path: '/' },
    { name: 'SID', value: 's', domain: '.google.com', path: '/' },
  ], '.youtube.com');
  assert.equal(count, 5, 'every cookie was accepted, the __Host- one included');
  const find = (name, domain) => jar.cookies.filter(c => c.name === name && c.domain === domain);
  assert.equal(find('VISITOR', '.youtube.com')[0].value, 'a');
  assert.equal(find('VISITOR', 'm.youtube.com')[0].value, 'b', 'the second copy did not delete the first');
  assert.equal(find('PREF', '.www.youtube.com').length, 0, 'the legacy widened copy is gone');
  assert.equal(find('PREF', 'www.youtube.com')[0].hostOnly, true);
  assert.equal(find('__Host-GAPS', 'accounts.google.com')[0].hostOnly, true);
  assert.equal(find('SID', '.twitch.tv')[0].value, 'other-site', 'another site keeps its same-named cookie');
});

test('issue-19: a pasted session YouTube rejects is undone exactly, the probe page\'s cookies included', () => {
  // A working session as ses.cookies.get returns it, plus neighbours that
  // are not the YouTube import's business.
  const live = [
    { name: 'SID', value: 'live-sid', domain: '.google.com', path: '/', hostOnly: false, httpOnly: true, secure: true, sameSite: 'unspecified', expirationDate: 1830000000.5 },
    { name: '__Secure-1PSID', value: 'live-psid', domain: '.google.com', path: '/', hostOnly: false, httpOnly: true, secure: true, sameSite: 'unspecified', expirationDate: 1830000000 },
    { name: 'LOGIN_INFO', value: 'li', domain: '.youtube.com', path: '/', hostOnly: false, httpOnly: true, secure: true, sameSite: 'no_restriction', expirationDate: 1830000000 },
    { name: 'PREF', value: 'f6=1', domain: 'www.youtube.com', path: '/', hostOnly: true, httpOnly: false, secure: true, sameSite: 'lax', expirationDate: 1830000000 },
    { name: '__Host-GAPS', value: 'gaps', domain: 'accounts.google.com', path: '/', hostOnly: true, httpOnly: true, secure: true, sameSite: 'unspecified', expirationDate: 1830000000 },
    { name: 'YSC', value: 'session', domain: '.youtube.com', path: '/', hostOnly: false, httpOnly: true, secure: true, sameSite: 'no_restriction', session: true },
  ];
  const neighbours = [
    { name: 'SID', value: 'twitch', domain: '.twitch.tv', path: '/', hostOnly: false },
    { name: 'OSID', value: 'mail', domain: 'mail.google.com', path: '/', hostOnly: true },
  ];
  const jar = createJar([...live, ...neighbours]);
  const before = youtubeJarCookies([...jar.get({ name: 'SID' }), ...jar.cookies, null, { name: 'x', domain: '.doubleclick.net' }]);
  assert.equal(before.length, live.length, 'the Google/YouTube session only, each cookie once');

  // The paste (a dead session), then cookies the probe page set for it.
  applyPlan(jar, [
    { name: 'SID', value: 'dead-sid', domain: '.google.com', path: '/', httpOnly: true },
    { name: '__Secure-1PSID', value: 'dead-psid', domain: '.google.com', path: '/', httpOnly: true },
    { name: 'PREF', value: 'f6=2', domain: 'www.youtube.com', path: '/' },
    { name: 'NEWONE', value: 'n', domain: '.youtube.com', path: '/' },
  ], '.youtube.com');
  jar.set({ url: 'https://google.com/', name: '__Secure-1PSIDCC', value: 'probe', path: '/', domain: '.google.com' });

  // restorePastedOver: clear the YouTube/Google cookies, write the copy back.
  for (const c of youtubeJarCookies(jar.cookies)) jar.remove(removalUrl(c), c.name);
  assert.equal(applyPlan(jar, before, '.youtube.com'), live.length, 'every cookie went back');

  const shape = (list) => list.map(c => `${c.name}|${c.domain}|${c.path}|${c.value}|${!!c.hostOnly}`).sort();
  assert.deepEqual(shape(youtubeJarCookies(jar.cookies)), shape(live), 'the session is exactly what it was');
  assert.deepEqual(shape(jar.cookies.filter(c => !youtubeJarCookies([c]).length)), shape(neighbours), 'nothing else was touched');

  // The attributes the model does not keep survive the round trip too.
  const writes = new Map(planCookieWrites(before, { defaultDomain: '.youtube.com', nowS: NOW_S }).writes.map(d => [`${d.name}|${d.domain || d.url}`, d]));
  const sid = writes.get('SID|.google.com');
  assert.equal(sid.httpOnly, true);
  assert.equal(sid.secure, true);
  assert.equal(sid.expirationDate, 1830000000.5);
  assert.equal(writes.get('LOGIN_INFO|.youtube.com').sameSite, 'no_restriction');
  const pref = writes.get('PREF|https://www.youtube.com/');
  assert.equal('domain' in pref, false, 'host-only stays host-only');
  assert.equal(pref.sameSite, 'lax');
  assert.equal('domain' in writes.get('__Host-GAPS|https://accounts.google.com/'), false);
  assert.equal(writes.get('YSC|.youtube.com').expirationDate, NOW_S + ONE_YEAR_S, 'a session cookie comes back for a year, as imports always did');
});

// r4-2: writeCookieList's loop (applyCookiePlan), asked about the import's
// ticket before every remove and set.

// The jar above behind Electron's async ses.cookies, logging each call. Every
// call waits a turn of the event loop, as a real one waits on the network
// service, so two imports running at once interleave call by call.
function asyncCookies(jar, { onCall = () => {} } = {}) {
  const calls = [];
  const turn = () => new Promise(r => setImmediate(r));
  return {
    calls,
    async get(q) { await turn(); return jar.get(q); },
    async remove(url, name) { calls.push(`remove ${name}`); onCall(calls); await turn(); jar.remove(url, name); },
    async set(d) { calls.push(`set ${d.name}`); onCall(calls); await turn(); jar.set(d); },
  };
}

const GOOGLE_NAMES = ['SID', 'HSID', 'SSID', '__Secure-1PSID', '__Secure-3PSID'];
const googleSession = (value, extra = []) => [
  ...GOOGLE_NAMES.map(name => ({ name, value, domain: '.google.com', path: '/', httpOnly: true })),
  ...extra,
];

test('r4-2: without a ticket the plan runs whole, the same as the loop it replaced', async () => {
  const initial = [
    { name: 'VISITOR', value: 'stale', domain: '.youtube.com', path: '/' },
    { name: 'PREF', value: 'legacy', domain: '.www.youtube.com', path: '/' },
    { name: 'SID', value: 'other-site', domain: '.twitch.tv', path: '/' },
  ];
  const list = [
    { name: 'VISITOR', value: 'a', domain: '.youtube.com', path: '/' },
    { name: 'VISITOR', value: 'b', domain: 'm.youtube.com', path: '/' },
    { name: 'PREF', value: 'new', domain: 'www.youtube.com', path: '/' },
    { name: '__Host-GAPS', value: 'g', domain: 'accounts.google.com', path: '/' },
    { name: 'SID', value: 's', domain: '.google.com', path: '/' },
  ];
  const oldLoop = createJar(initial);
  const viaPlan = createJar(initial);
  const count = applyPlan(oldLoop, list, '.youtube.com');
  const r = await applyCookiePlan(planCookieWrites(list, { defaultDomain: '.youtube.com', nowS: NOW_S }), asyncCookies(viaPlan));
  assert.deepEqual(r, { set: count, stopped: false });
  assert.deepEqual(viaPlan.cookies, oldLoop.cookies);

  // A cookie Chromium refuses is reported and the rest are still written.
  const errors = [];
  const refusing = { ...asyncCookies(createJar()), async set(d) { if (d.name === 'HSID') throw new Error('refused'); } };
  const r2 = await applyCookiePlan(planCookieWrites(googleSession('v'), { nowS: NOW_S }), refusing, {
    onSetError: (d, e) => errors.push(`${d.name}: ${e.message}`),
  });
  assert.deepEqual(r2, { set: GOOGLE_NAMES.length - 1, stopped: false });
  assert.deepEqual(errors, ['HSID: refused']);
});

test('r4-2 regression: a re-sync whose ticket is taken between two writes removes and sets nothing more', async () => {
  const tickets = createSyncTickets();
  const ticket = tickets.take('youtube', { auto: true, isBlocked: () => false });
  const jar = createJar(googleSession('app').map(c => ({ ...c })));
  // A paste (or a Sign Out, or a login in the app) lands while the second
  // set is on its way.
  const cookies = asyncCookies(jar, {
    onCall: (calls) => { if (calls.filter(c => c.startsWith('set ')).length === 2) tickets.bump('youtube'); },
  });
  const plan = planCookieWrites(googleSession('browser'), { nowS: NOW_S });
  const r = await applyCookiePlan(plan, cookies, { stillValid: ticket.valid });
  assert.deepEqual(r, { set: 2, stopped: true });
  assert.deepEqual(cookies.calls, [
    ...GOOGLE_NAMES.map(n => `remove ${n}`),
    'set SID', 'set HSID', // the one already sent when the ticket went lands; nothing after it
  ]);
  assert.equal(ticket.valid(), false, 'so the importer undoes instead of saving the account');
});

test('r4-2 regression: a ticket taken during the clear phase stops the next remove, and nothing is set', async () => {
  const tickets = createSyncTickets();
  const ticket = tickets.take('twitch', { auto: true, isBlocked: () => false });
  const jar = createJar([
    { name: 'auth-token', value: 'app', domain: '.twitch.tv', path: '/' },
    { name: 'unique_id', value: 'app', domain: '.twitch.tv', path: '/' },
    { name: 'persistent', value: 'app', domain: '.twitch.tv', path: '/' },
  ]);
  const cookies = asyncCookies(jar, { onCall: (calls) => { if (calls.length === 1) tickets.bump('twitch'); } });
  const list = ['auth-token', 'unique_id', 'persistent'].map(name => ({ name, value: 'browser', domain: '.twitch.tv', path: '/' }));
  const r = await applyCookiePlan(planCookieWrites(list, { nowS: NOW_S }), cookies, { stillValid: ticket.valid });
  assert.deepEqual(r, { set: 0, stopped: true });
  assert.deepEqual(cookies.calls, ['remove auth-token']);
  assert.deepEqual(jar.cookies.map(c => `${c.name}=${c.value}`), ['unique_id=app', 'persistent=app'], 'the rest of the jar is untouched');
});

// The failure the reviewer described: the extension's YouTube re-sync is part
// way through ~60 cookies when a paste is submitted. The paste ends the
// re-sync's ticket (importGoogleSession's bump) and runs its own clear and
// write. Both loops then ran interleaved at every await.
async function pasteDuringResync({ resyncStops }) {
  const tickets = createSyncTickets();
  const ticket = tickets.take('youtube', { auto: true, isBlocked: () => false });
  const jar = createJar(googleSession('app').map(c => ({ ...c })));
  const filler = Array.from({ length: 50 }, (_, i) => ({ name: `Y${i}`, value: 'browser', domain: '.youtube.com', path: '/' }));
  let paste = null;
  const resyncCookies = asyncCookies(jar, {
    onCall: (calls) => {
      if (calls.length !== 3 || paste) return;
      tickets.bump('youtube'); // set-google-cookies -> importGoogleSession
      paste = applyCookiePlan(planCookieWrites(googleSession('paste'), { nowS: NOW_S }), asyncCookies(jar));
    },
  });
  const resync = applyCookiePlan(
    planCookieWrites(googleSession('browser', filler), { nowS: NOW_S }),
    resyncCookies,
    resyncStops ? { stillValid: ticket.valid } : {},
  );
  const r = await resync;
  assert.ok(paste, 'the paste started part way through the re-sync');
  const pasted = await paste;
  const google = jar.cookies.filter(c => GOOGLE_NAMES.includes(c.name)).map(c => `${c.name}=${c.value}`).sort();
  return { r, pasted, google, all: jar.cookies };
}

test('r4-2 regression: a paste submitted during a YouTube re-sync ends up as the whole Google session', async () => {
  const { r, pasted, google, all } = await pasteDuringResync({ resyncStops: true });
  assert.equal(r.stopped, true);
  assert.deepEqual(pasted, { set: GOOGLE_NAMES.length, stopped: false });
  assert.deepEqual(google, GOOGLE_NAMES.map(n => `${n}=paste`).sort(), 'every Google sign-in cookie is the paste\'s');
  assert.equal(all.filter(c => c.value === 'browser').length, 0, 'the re-sync wrote nothing after the paste began');

  // The same run with the loop that ignored the ticket leaves browser
  // cookies over the paste: the test catches the bug it guards.
  const unguarded = await pasteDuringResync({ resyncStops: false });
  assert.equal(unguarded.r.stopped, false);
  assert.notDeepEqual(unguarded.google, GOOGLE_NAMES.map(n => `${n}=paste`).sort());
});

test('C1: YouTube imports keep youtube.com (any subdomain) and exactly google.com / accounts.google.com', () => {
  for (const d of ['youtube.com', '.youtube.com', 'www.youtube.com', '.www.youtube.com', 'm.youtube.com', 'google.com', '.google.com', 'accounts.google.com', '.accounts.google.com']) {
    assert.equal(isYouTubeCookieDomain(d), true, d);
  }
  for (const d of ['', 'mail.google.com', '.myaccount.google.com', 'youtube-nocookie.com', 'ytimg.com', 'gstatic.com', 'googleapis.com', 'evilyoutube.com', 'google.com.evil.com', 'google.co.uk']) {
    assert.equal(isYouTubeCookieDomain(d), false, d);
  }
});

test('issue-4: a domain that is not a bare hostname is refused by every platform filter and never written', () => {
  // Each passes a plain suffix match and, being dotless, used to count as
  // host-only: written to https://<everything before the path>/, a cookie
  // on attacker.example or www.twitch.tv.
  const crafted = [
    ['attacker.example/.youtube.com', 'youtube.com'],
    ['evil.com?.twitch.tv', 'twitch.tv'],
    ['www.twitch.tv/.kick.com', 'kick.com'],
    ['.attacker.example/.youtube.com', 'youtube.com'],
    ['evil.com#.kick.com', 'kick.com'],
    ['evil.com\\.twitch.tv', 'twitch.tv'],
    ['user@evil.com.youtube.com', 'youtube.com'],
    ['evil.com:443.kick.com', 'kick.com'],
    ['evil.com .twitch.tv', 'twitch.tv'],
    ['..youtube.com', 'youtube.com'],
    ['youtube.com.', 'youtube.com'],
  ];
  for (const [domain, site] of crafted) {
    assert.equal(isCookieHost(domain), false, domain);
    assert.equal(isCookieDomainOf(domain, site), false, domain);
    assert.equal(cookieSetDetails({ name: 'SID', value: 'v', domain }, { nowS: NOW_S }), null, domain);
    assert.equal(cookieSetDetails({ name: 'SID', value: 'v', domain, hostOnly: false }, { nowS: NOW_S }), null, domain);
  }
  for (const domain of ['attacker.example/.youtube.com', 'evil.com?.google.com', 'x/.accounts.google.com']) {
    assert.equal(isYouTubeCookieDomain(domain), false, domain);
  }
  // Nothing crafted reaches a write, and nothing is cleared on its account.
  const plan = planCookieWrites(crafted.map(([domain]) => ({ name: 'auth-token', value: 'v', domain })), { nowS: NOW_S });
  assert.deepEqual(plan.writes, []);
  assert.equal(plan.clear.size, 0);
  // Real domains still pass, host-only and domain cookies alike.
  for (const [domain, site] of [['kick.com', 'kick.com'], ['.kick.com', 'kick.com'], ['www.twitch.tv', 'twitch.tv'], ['.twitch.tv', 'twitch.tv'], ['gql.twitch.tv', 'twitch.tv'], ['WWW.YouTube.com', 'youtube.com']]) {
    assert.equal(isCookieDomainOf(domain, site), true, domain);
    assert.ok(cookieSetDetails({ name: 'n', value: 'v', domain }, { nowS: NOW_S }), domain);
  }
  for (const [domain, site] of [['notkick.com', 'kick.com'], ['kick.com.evil.com', 'kick.com'], ['twitch.tv.evil', 'twitch.tv'], ['', 'kick.com']]) {
    assert.equal(isCookieDomainOf(domain, site), false, domain);
  }
  // A cookie with no domain of its own still takes the import's default.
  assert.equal(cookieSetDetails({ name: 'n', value: 'v' }, { defaultDomain: '.kick.com', nowS: NOW_S }).url, 'https://kick.com/');
});

test('issue-4: the Kick and Twitch imports filter through isCookieDomainOf', () => {
  const mainJs = require('fs').readFileSync(require('path').join(__dirname, '..', 'main.js'), 'utf8').replace(/\r\n/g, '\n');
  const body = (marker) => mainJs.slice(mainJs.indexOf(marker), mainJs.indexOf('\n}\n', mainJs.indexOf(marker)));
  assert.match(body('async function importTwitchSession('), /\.filter\(c => c && c\.name && isCookieDomainOf\(c\.domain, 'twitch\.tv'\)\)/);
  assert.match(body('async function importKickSession('), /\.filter\(c => c && isCookieDomainOf\(c\.domain, 'kick\.com'\)\)/);
  // No suffix-only regex is left on an import path.
  assert.doesNotMatch(mainJs, /\/\(\^\|\\\.\)(kick\\\.com|twitch\\\.tv)\$\//);
});

test('F40: a DevTools Cookie header becomes .youtube.com domain cookies and is accepted', () => {
  const header = 'VISITOR_INFO1_LIVE=v; SID=s; HSID=h; SSID=ss; APISID=a; SAPISID=sa; __Secure-1PSID=p; LOGIN_INFO=l; __Host-3PLSID=x';
  const list = assignPastedYouTubeDomains(parseCookieBlob(header));
  assert.ok(list.every(c => isYouTubeCookieDomain(c.domain)), 'nothing is dropped by the domain filter');
  assert.equal(hasGoogleSessionCookies(list), true);
  const details = list.map(c => cookieSetDetails(c, { defaultDomain: '.youtube.com', nowS: NOW_S }));
  const sid = details.find(d => d.name === 'SID');
  assert.equal(sid.domain, '.youtube.com', 'a domain cookie, so www.youtube.com receives it');
  const host = details.find(d => d.name === '__Host-3PLSID');
  assert.equal('domain' in host, false, '__Host- never gets a Domain');
  assert.equal(host.url, 'https://www.youtube.com/', 'host-only on www, never the apex');
});

test('F40: a document.cookie paste is refused (its httpOnly session cookies are missing)', () => {
  const docCookie = 'VISITOR_INFO1_LIVE=v; PREF=f6=4; SID=s; APISID=a; SAPISID=sa; __Secure-1PAPISID=pa; __Secure-3PAPISID=pa3';
  const list = assignPastedYouTubeDomains(parseCookieBlob(docCookie));
  assert.equal(hasGoogleSessionCookies(list), false);
});

test('hasGoogleSessionCookies needs __Secure-*PSID, or SID with HSID and SSID, with values', () => {
  const c = (...names) => names.map(n => ({ name: n, value: 'v' }));
  assert.equal(hasGoogleSessionCookies(c('__Secure-1PSID')), true);
  assert.equal(hasGoogleSessionCookies(c('__Secure-3PSID')), true);
  assert.equal(hasGoogleSessionCookies(c('SID', 'HSID', 'SSID')), true);
  assert.equal(hasGoogleSessionCookies(c('SID', 'HSID')), false);
  assert.equal(hasGoogleSessionCookies(c('SID', 'APISID', 'SAPISID', 'LSID')), false);
  assert.equal(hasGoogleSessionCookies([{ name: '__Secure-1PSID', value: '' }]), false);
  assert.equal(hasGoogleSessionCookies(null), false);
});

test('pasted cookies that carry their own domain are left alone', () => {
  const list = assignPastedYouTubeDomains([{ name: 'SID', value: 's', domain: '.google.com' }, null]);
  assert.equal(list[0].domain, '.google.com');
  assert.equal(list[1], null);
});
