// F38 / F39 / F40: parsing pasted cookie exports and shaping the cookies.set
// calls that reproduce them. Chromium's rules that bit are modelled in a tiny
// jar below: a __Host- cookie with a Domain is rejected, a host-only cookie
// written with a Domain becomes a domain cookie, and removal happens before
// writes. Run: npm test
const test = require('node:test');
const assert = require('node:assert/strict');
const {
  parseCookieBlob, normalizeExpiry, isHostOnlyCookie, cookieSetDetails, planCookieWrites,
  shouldClearExisting, removalUrl, isYouTubeCookieDomain, assignPastedYouTubeDomains, hasGoogleSessionCookies,
} = require('../main/cookie-import');

const NOW_S = 1_800_000_000;
const ONE_YEAR_S = 60 * 60 * 24 * 365;

// A curl-style cookies.txt, as "Get cookies.txt LOCALLY" writes it: httpOnly
// cookies carry a #HttpOnly_ prefix, CRLF line ends, a session cookie has 0.
const NETSCAPE = [
  '# Netscape HTTP Cookie File',
  '# This file was generated by Get cookies.txt LOCALLY',
  '',
  '#HttpOnly_.google.com\tTRUE\t/\tTRUE\t1830000000\tSID\tsid-google',
  '#HttpOnly_.google.com\tTRUE\t/\tTRUE\t1830000000\tHSID\thsid-google',
  '#HttpOnly_.google.com\tTRUE\t/\tTRUE\t1830000000\tSSID\tssid-google',
  '#HttpOnly_.google.com\tTRUE\t/\tTRUE\t1830000000\t__Secure-1PSID\tpsid-google',
  '.google.com\tTRUE\t/\tTRUE\t1830000000\tSAPISID\tsapisid-google ',
  '.youtube.com\tTRUE\t/\tTRUE\t0\tYSC\tysc-session',
  '#HttpOnly_accounts.google.com\tFALSE\t/\tTRUE\t1830000000\t__Host-GAPS\tgaps',
  'www.youtube.com\tFALSE\t/\tFALSE\t1830000000\tPREF\tf6=40000000',
].join('\r\n');

test('F38: cookies.txt keeps #HttpOnly_ lines as httpOnly cookies and still skips real comments', () => {
  const out = parseCookieBlob(NETSCAPE);
  const byName = Object.fromEntries(out.map(c => [c.name, c]));
  assert.deepEqual(Object.keys(byName).sort(), ['HSID', 'PREF', 'SAPISID', 'SID', 'SSID', 'YSC', '__Host-GAPS', '__Secure-1PSID']);
  assert.equal(byName.SID.httpOnly, true);
  assert.equal(byName.SID.domain, '.google.com', 'prefix stripped, domain intact');
  assert.equal(byName['__Secure-1PSID'].httpOnly, true);
  assert.equal(byName.SAPISID.httpOnly, false);
  assert.equal(byName.SAPISID.value, 'sapisid-google', 'trailing whitespace trimmed');
  assert.equal(byName.YSC.expirationDate, undefined, 'expiry 0 is a session cookie');
  assert.equal(byName['__Host-GAPS'].domain, 'accounts.google.com');
  assert.equal(byName['__Host-GAPS'].hostOnly, true, 'includeSubdomains FALSE on a dotless domain');
  assert.equal(byName.PREF.hostOnly, true);
  assert.equal(byName.SID.hostOnly, false);
  // The import gate now passes on the real session identifiers...
  assert.equal(hasGoogleSessionCookies(out), true);
  // ...and the same file with its httpOnly lines lost (what the old parser
  // produced) is refused instead of reported as a success.
  const stripped = parseCookieBlob(NETSCAPE.split('\r\n').filter(l => !l.startsWith('#HttpOnly_')).join('\n'));
  assert.equal(hasGoogleSessionCookies(stripped), false);
});

test('F38: a leading dot means a domain cookie whatever the flag says; TRUE on a dotless domain too', () => {
  const out = parseCookieBlob('.kick.com\tFALSE\t/\tTRUE\t1830000000\ta\t1\nkick.com\tTRUE\t/\tTRUE\t1830000000\tb\t2');
  assert.equal(out[0].hostOnly, false);
  assert.equal(out[1].hostOnly, false);
  assert.equal(cookieSetDetails(out[1], { nowS: NOW_S }).domain, 'kick.com', 'kept as a domain cookie');
});

test('F38: JSON expiry: -1, 0, milliseconds, date strings, session flag', () => {
  const out = parseCookieBlob(JSON.stringify([
    { name: 'a', value: '1', domain: '.youtube.com', expires: -1 },
    { name: 'b', value: '1', domain: '.youtube.com', expires: 0 },
    { name: 'c', value: '1', domain: '.youtube.com', expires: 1830000000123 },
    { name: 'd', value: '1', domain: '.youtube.com', expires: '2028-01-01T00:00:00Z' },
    { name: 'e', value: '1', domain: '.youtube.com', expirationDate: 1830000000.5 },
    { name: 'f', value: '1', domain: '.youtube.com', expirationDate: 1830000000, session: true },
    { name: 'g', value: '1', domain: 'www.youtube.com', hostOnly: true, expirationDate: -1 },
  ]));
  const exp = Object.fromEntries(out.map(c => [c.name, c.expirationDate]));
  assert.equal(exp.a, undefined);
  assert.equal(exp.b, undefined);
  assert.equal(exp.c, 1830000000.123);
  assert.equal(exp.d, Date.parse('2028-01-01T00:00:00Z') / 1000);
  assert.equal(exp.e, 1830000000.5);
  assert.equal(exp.f, undefined);
  assert.equal(out.find(c => c.name === 'g').hostOnly, true);
  // A session cookie written as -1 would be dropped by Chromium on the spot;
  // it gets the writer's one-year default instead.
  assert.equal(cookieSetDetails(out[0], { nowS: NOW_S }).expirationDate, NOW_S + ONE_YEAR_S);
  assert.equal(cookieSetDetails({ name: 'x', value: '1', domain: '.a.com', expirationDate: -1 }, { nowS: NOW_S }).expirationDate, NOW_S + ONE_YEAR_S);
});

test('normalizeExpiry rejects everything that is not a positive time', () => {
  for (const v of [undefined, null, '', 'Session', NaN, Infinity, -5, 0, '0', {}, []]) {
    assert.equal(normalizeExpiry(v), undefined, String(v));
  }
  assert.equal(normalizeExpiry('1830000000'), 1830000000);
});

test('F39: __Host- cookies are written without a Domain, on path /, secure', () => {
  // As the extension sends it: chrome.cookies domain, no hostOnly field.
  const d = cookieSetDetails({ name: '__Host-GAPS', value: 'g', domain: 'accounts.google.com', path: '/', secure: true, httpOnly: true, sameSite: 'lax', expirationDate: 1830000000 }, { defaultDomain: '.youtube.com', nowS: NOW_S });
  assert.equal('domain' in d, false, 'no domain key at all');
  assert.equal(d.url, 'https://accounts.google.com/');
  assert.equal(d.path, '/');
  assert.equal(d.secure, true);
  assert.equal(d.httpOnly, true);
  // Even an exporter that got the path or the secure flag wrong.
  const odd = cookieSetDetails({ name: '__Host-1PLSID', value: 'x', domain: 'accounts.google.com', path: '/x', secure: false }, { nowS: NOW_S });
  assert.equal(odd.path, '/');
  assert.equal(odd.secure, true);
  assert.equal('domain' in odd, false);
  assert.equal(cookieSetDetails({ name: '__Secure-3PSID', value: 'x', domain: '.google.com', secure: false }, { nowS: NOW_S }).secure, true);
});

test('F39: host-only stays host-only, domain cookies keep their Domain, domain-less keeps the default', () => {
  const host = cookieSetDetails({ name: 'PREF', value: 'p', domain: 'www.youtube.com' }, { defaultDomain: '.youtube.com', nowS: NOW_S });
  assert.equal('domain' in host, false);
  assert.equal(host.url, 'https://www.youtube.com/');
  const dom = cookieSetDetails({ name: 'SID', value: 's', domain: '.youtube.com' }, { defaultDomain: '.youtube.com', nowS: NOW_S });
  assert.equal(dom.domain, '.youtube.com');
  assert.equal(dom.url, 'https://youtube.com/');
  const flagged = cookieSetDetails({ name: 'x', value: 'v', domain: 'kick.com', hostOnly: true }, { nowS: NOW_S });
  assert.equal('domain' in flagged, false);
  // A synthesized cookie with no domain of its own (the Twitch login cookie
  // path, a header paste) stays a domain cookie on the default, as before.
  const synth = cookieSetDetails({ name: 'login', value: 'me' }, { defaultDomain: '.twitch.tv', nowS: NOW_S });
  assert.equal(synth.domain, '.twitch.tv');
  assert.equal(cookieSetDetails({ name: 'n', value: 'v' }, {}), null, 'no domain anywhere');
  assert.equal(isHostOnlyCookie({ name: 'a', domain: '.x.com', hostOnly: true }), true, 'an explicit flag wins');
});

test('SameSite=None on an insecure cookie is downgraded instead of rejected', () => {
  const d = cookieSetDetails({ name: 'PREF', value: 'p', domain: 'www.youtube.com', secure: false, sameSite: 'no_restriction' }, { nowS: NOW_S });
  assert.equal(d.secure, false);
  assert.equal(d.sameSite, 'unspecified');
});

// Chromium's cookie store, reduced to the rules above.
function createJar(initial = []) {
  const cookies = initial.map(c => ({ ...c }));
  const key = (c) => `${c.name}|${c.domain}|${c.path}`;
  return {
    cookies,
    get({ name }) { return cookies.filter(c => c.name === name).map(c => ({ ...c })); },
    remove(url, name) {
      const u = new URL(url);
      for (let i = cookies.length - 1; i >= 0; i--) {
        const c = cookies[i];
        const host = c.domain.replace(/^\./, '');
        const matches = c.domain.startsWith('.') ? (u.hostname === host || u.hostname.endsWith('.' + host)) : u.hostname === host;
        if (c.name === name && matches && u.pathname.startsWith(c.path)) cookies.splice(i, 1);
      }
    },
    set(d) {
      if (d.name.startsWith('__Host-') && 'domain' in d) throw new Error('Failed to set cookie with an invalid domain attribute');
      const u = new URL(d.url);
      const c = { name: d.name, value: d.value, path: d.path, domain: 'domain' in d ? (d.domain.startsWith('.') ? d.domain : '.' + d.domain) : u.hostname, hostOnly: !('domain' in d) };
      const i = cookies.findIndex(x => key(x) === key(c));
      if (i >= 0) cookies.splice(i, 1);
      cookies.push(c);
    },
  };
}

function applyPlan(jar, list, defaultDomain) {
  const plan = planCookieWrites(list, { defaultDomain, nowS: NOW_S });
  for (const name of plan.clear.keys()) {
    for (const ex of jar.get({ name })) if (shouldClearExisting(ex, plan)) jar.remove(removalUrl(ex), name);
  }
  let count = 0;
  for (const d of plan.writes) { try { jar.set(d); count++; } catch (e) { /* counted as failed */ } }
  return count;
}

test('F39: one import can hold the same name on two hosts of a site; both survive', () => {
  const jar = createJar([
    { name: 'VISITOR', value: 'stale', domain: '.youtube.com', path: '/' },
    // What older builds wrote for a host-only cookie.
    { name: 'PREF', value: 'legacy', domain: '.www.youtube.com', path: '/' },
    { name: 'SID', value: 'other-site', domain: '.twitch.tv', path: '/' },
  ]);
  const count = applyPlan(jar, [
    { name: 'VISITOR', value: 'a', domain: '.youtube.com', path: '/' },
    { name: 'VISITOR', value: 'b', domain: 'm.youtube.com', path: '/' },
    { name: 'PREF', value: 'new', domain: 'www.youtube.com', path: '/' },
    { name: '__Host-GAPS', value: 'g', domain: 'accounts.google.com', path: '/' },
    { name: 'SID', value: 's', domain: '.google.com', path: '/' },
  ], '.youtube.com');
  assert.equal(count, 5, 'every cookie was accepted, the __Host- one included');
  const find = (name, domain) => jar.cookies.filter(c => c.name === name && c.domain === domain);
  assert.equal(find('VISITOR', '.youtube.com')[0].value, 'a');
  assert.equal(find('VISITOR', 'm.youtube.com')[0].value, 'b', 'the second copy did not delete the first');
  assert.equal(find('PREF', '.www.youtube.com').length, 0, 'the legacy widened copy is gone');
  assert.equal(find('PREF', 'www.youtube.com')[0].hostOnly, true);
  assert.equal(find('__Host-GAPS', 'accounts.google.com')[0].hostOnly, true);
  assert.equal(find('SID', '.twitch.tv')[0].value, 'other-site', 'another site keeps its same-named cookie');
});

test('C1: YouTube imports keep youtube.com (any subdomain) and exactly google.com / accounts.google.com', () => {
  for (const d of ['youtube.com', '.youtube.com', 'www.youtube.com', '.www.youtube.com', 'm.youtube.com', 'google.com', '.google.com', 'accounts.google.com', '.accounts.google.com']) {
    assert.equal(isYouTubeCookieDomain(d), true, d);
  }
  for (const d of ['', 'mail.google.com', '.myaccount.google.com', 'youtube-nocookie.com', 'ytimg.com', 'gstatic.com', 'googleapis.com', 'evilyoutube.com', 'google.com.evil.com', 'google.co.uk']) {
    assert.equal(isYouTubeCookieDomain(d), false, d);
  }
});

test('F40: a DevTools Cookie header becomes .youtube.com domain cookies and is accepted', () => {
  const header = 'VISITOR_INFO1_LIVE=v; SID=s; HSID=h; SSID=ss; APISID=a; SAPISID=sa; __Secure-1PSID=p; LOGIN_INFO=l; __Host-3PLSID=x';
  const list = assignPastedYouTubeDomains(parseCookieBlob(header));
  assert.ok(list.every(c => isYouTubeCookieDomain(c.domain)), 'nothing is dropped by the domain filter');
  assert.equal(hasGoogleSessionCookies(list), true);
  const details = list.map(c => cookieSetDetails(c, { defaultDomain: '.youtube.com', nowS: NOW_S }));
  const sid = details.find(d => d.name === 'SID');
  assert.equal(sid.domain, '.youtube.com', 'a domain cookie, so www.youtube.com receives it');
  const host = details.find(d => d.name === '__Host-3PLSID');
  assert.equal('domain' in host, false, '__Host- never gets a Domain');
  assert.equal(host.url, 'https://www.youtube.com/', 'host-only on www, never the apex');
});

test('F40: a document.cookie paste is refused (its httpOnly session cookies are missing)', () => {
  const docCookie = 'VISITOR_INFO1_LIVE=v; PREF=f6=4; SID=s; APISID=a; SAPISID=sa; __Secure-1PAPISID=pa; __Secure-3PAPISID=pa3';
  const list = assignPastedYouTubeDomains(parseCookieBlob(docCookie));
  assert.equal(hasGoogleSessionCookies(list), false);
});

test('hasGoogleSessionCookies needs __Secure-*PSID, or SID with HSID and SSID, with values', () => {
  const c = (...names) => names.map(n => ({ name: n, value: 'v' }));
  assert.equal(hasGoogleSessionCookies(c('__Secure-1PSID')), true);
  assert.equal(hasGoogleSessionCookies(c('__Secure-3PSID')), true);
  assert.equal(hasGoogleSessionCookies(c('SID', 'HSID', 'SSID')), true);
  assert.equal(hasGoogleSessionCookies(c('SID', 'HSID')), false);
  assert.equal(hasGoogleSessionCookies(c('SID', 'APISID', 'SAPISID', 'LSID')), false);
  assert.equal(hasGoogleSessionCookies([{ name: '__Secure-1PSID', value: '' }]), false);
  assert.equal(hasGoogleSessionCookies(null), false);
});

test('pasted cookies that carry their own domain are left alone', () => {
  const list = assignPastedYouTubeDomains([{ name: 'SID', value: 's', domain: '.google.com' }, null]);
  assert.equal(list[0].domain, '.google.com');
  assert.equal(list[1], null);
});
